version: "3.9"

services:
  db_booking:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_booking
      MARIADB_ROOT_PASSWORD: ThePassword
    ports:
        - "3306:3306"
    container_name: db_booking
  
  db_product:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_product
      MARIADB_ROOT_PASSWORD: ThePassword
    ports:
        - "3307:3306"
    container_name: db_product

  db_stock:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_stock
      MARIADB_ROOT_PASSWORD: ThePassword
    ports:
        - "3308:3306"
    container_name: db_stock

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    container_name: discovery-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    container_name: api-gateway

  booking-service:
    build: ./booking
    ports:
      - "8081"
    container_name: booking-service
    environment:
      - DB_URL=jdbc:mariadb://db_booking:3306/db_booking
      - DB_USER=springuser
      - DB_PASS=ThePassword
    depends_on:
      - db_booking
      - discovery-service
      - api-gateway
  
  product-service:
    build: ./product
    ports:
      - "8082"
    container_name: product-service
    environment:
      - DB_URL=jdbc:mariadb://db_product:3306/db_product
      - DB_USER=springuser
      - DB_PASS=ThePassword
    depends_on:
      - db_product
      - discovery-service
      - api-gateway

  stock-mocroservice:
    build: ./stock
    ports:
      - "8083"
    container_name: stock-microservice
    environment:
      - DB_URL=jdbc:mariadb://db_stock:3306/db_stock
      - DB_USER=springuser
      - DB_PASS=ThePassword
    depends_on:
      - db_stock
      - discovery-service
      - api-gateway

  file-microservice:
    build: ./fileStore
    ports:
      - "8084"
    container_name: file-microservice
    depends_on:
      - discovery-service
      - api-gateway
    volumes:
      - image_volume:/mnt/image_volume/

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - image_volume:/usr/share/nginx/html
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    volumes:
      - ./keycloak-server/realm-export.json:/tmp/realm-export.json
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    command: ["start-dev", "--import-realm"]
    ports:
      - "9090:8080"
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  
volumes:
  image_volume:
  postgres_data:
