version: "3.9"

services:
  db_booking:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_booking
      MARIADB_ROOT_PASSWORD: ThePassword
    ports:
        - "3306:3306"
    container_name: db_booking
  
  db_product:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_product
      MARIADB_ROOT_PASSWORD: ThePassword
    ports:
        - "3307:3306"
    container_name: db_product

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    container_name: discovery-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    container_name: api-gateway

  booking-service:
    build: ./booking
    ports:
      - "8081"
    container_name: booking-service
    environment:
      - DB_URL=jdbc:mariadb://db_booking:3306/db_booking
      - DB_USER=springuser
      - DB_PASS=ThePassword
    depends_on:
      - db_booking
      - discovery-service
      - api-gateway
  
  product-service:
    build: ./product
    ports:
      - "8082"
    container_name: product-service
    environment:
      - DB_URL=jdbc:mariadb://db_product:3306/db_product
      - DB_USER=springuser
      - DB_PASS=ThePassword
    depends_on:
      - db_product
      - discovery-service
      - api-gateway

  file-microservice:
    build: ./fileStore
    ports:
      - "8083"
    container_name: file-microservice
    depends_on:
      - discovery-service
      - api-gateway
    volumes:
      - image_volume:/mnt/image_volume/

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - image_volume:/usr/share/nginx/html
    
volumes:
  image_volume:
