version: "3.9"

services:
  db_booking:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: db_booking
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
        - "3306:3306"
    container_name: db_booking
  
  db_product:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: db_product
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
        - "3307:3306"
    container_name: db_product

  db_stock:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: db_stock
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
        - "3308:3306"
    container_name: db_stock

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    container_name: discovery-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    container_name: api-gateway

  booking-microservice:
    build: ./booking
    container_name: booking-microservice
    environment:
      - DB_URL=${DB_URL_BOOKING}
      - DB_USER=${MARIADB_USER}
      - DB_PASS=${MARIADB_PASSWORD}
    depends_on:
      - db_booking
      - discovery-service
      - api-gateway
  
  product-microservice:
    build: ./product
    container_name: product-microservice
    environment:
      - DB_URL=${DB_URL_PRODUCT}
      - DB_USER=${MARIADB_USER}
      - DB_PASS=${MARIADB_PASSWORD}
    depends_on:
      - db_product
      - discovery-service
      - api-gateway

  stock-microservice:
    build: ./stock
    container_name: stock-microservice
    environment:
      - DB_URL=${DB_URL_STOCK}
      - DB_USER=${MARIADB_USER}
      - DB_PASS=${MARIADB_PASSWORD}
    depends_on:
      - db_stock
      - discovery-service
      - api-gateway

  file-microservice:
    build: ./fileStore
    ports:
      - "8084"
    container_name: file-microservice
    depends_on:
      - discovery-service
      - api-gateway
    volumes:
      - image_volume:/mnt/image_volume/

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - image_volume:/usr/share/nginx/html

volumes:
  image_volume:



