spring:
 application:
   name: api-gateway
 cloud:
   gateway:
     mvc:
       routes:
         - id: product-microservice
           uri: lb://PRODUCT-MICROSERVICE
           predicates:
             - Path=/product/**
         - id: booking-microservice
           uri: lb://BOOKING-MICROSERVICE
           predicates:
             - Path=/booking/**
         - id: file-microservice
           uri: lb://FILE-MICROSERVICE
           predicates:
            - Path=/file/**
eureka:
 client:
  service-url:
   defaultZone: http://discovery-service:8761/eureka/
 instance:
   instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 8080