spring:
 application:
   name: api-gateway
 cloud:
   gateway:
     mvc:
       routes:
         - id: product-microservice
           uri: lb://PRODUCT-MICROSERVICE
           predicates:
             - Path=/product/**
         - id: booking-microservice
           uri: lb://BOOKING-MICROSERVICE
           predicates:
             - Path=/booking/**
         - id: file-microservice
           uri: lb://FILE-MICROSERVICE
           predicates:
            - Path=/file/**
 security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/mycompany-microservices-realm
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1ZDM0OTkzMC01YWVmLTQwYmYtYjEzYi1mNmY5Njk4ZmViNDQifQ.eyJleHAiOjE3MTI3OTI0ODYsImlhdCI6MTcxMjcwNjA4NiwianRpIjoiOGQ5YmIyMWItOTYyNS00MDA1LWIyYjctYmYwNzg0NzY3MGQ3IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDkwL3JlYWxtcy9teWNvbXBhbnktbWljcm9zZXJ2aWNlcy1yZWFsbSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTA5MC9yZWFsbXMvbXljb21wYW55LW1pY3Jvc2VydmljZXMtcmVhbG0iLCJ0eXAiOiJJbml0aWFsQWNjZXNzVG9rZW4ifQ.iovqlZU5IZ_AwQzrVJsWX20WMo8Xgn5Zzla6ghhsJSVS-Mo0RYBRBo5u0fSeqaTc91xSwmTb7Bh3GCvFOqCoGA
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client

eureka:
 client:
  service-url:
   defaultZone: http://discovery-service:8761/eureka/
 instance:
   instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 8080